const users = [
  {
    firstName: "John",
    lastName: "Doe",
    age: 40,
    gender: "Male",
    height: 1.8,
    driversLicense: true,
    yearsOfDrivingExperience: 10,
    placeOfBirth: "Belgium",
    nationalities: ["spain", "belguim", "france"],
    children: [
      {
        firstname: "Melissa",
        lastname: "Doe",
        age: "7",
        gender: "Female",
        height: 1.2,
        birthPlace: "Colombia",
        nationalities: ["belgium", "spain"],
      },
      {
        firstname: "Ana",
        lastname: "Doe",
        age: 5,
        gender: "Female",
        birthPlace: "Belgium",
        nationalities: ["belgium"],
      },
    ],
  },
  {
    firstName: "Emma",
    lastName: "Smith",
    age: 21,
    gender: "Female",
    heigth: 1.65,
    hasDriversLicense: false,
    yearsOfDrivingExperience: 0,
    placeOfBirth: "Canada",
    nationatilies: ["canada", "uk"],
    children: [
      {
        firstname: "Lisa",
        lastname: "Smith",
        age: 1,
        gender: "Female",
        birthPlace: "Belgium",
        nationalities: ["belgium"],
      },
    ],
  },
  {
    firstname: "Carlos",
    lastname: "Martinez",
    age: 45,
    gender: "Male",
    heigth: 1.9,
    hasDriversLicense: false,
    yearsOfDrivingExperience: 0,
    placeOfBirth: "Mexico",
    nationalities: ["mexico"],
    children: [
      {
        firstname: "Mateo",
        lastname: "Martinez",
        age: "7",
        gender: "Male",
        height: 1.2,
        birthPlace: "Mexico",
        nationalities: ["méxico", "usa"],
      },
    ],
  },
];

export default users;
